spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: adminModule
        uri: lb://admin-service
        predicates:
        - Path=/admin/**
      - id: registrationModule
        uri: lb://registration-service
        predicates:
        - Path=/registration/**
      - id: assessmentModule
        uri: http://localhost:8083/
#        uri: lb://assessment-service
        predicates:
          - Path=/assessments/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/